[project]
name = "ignition-to-pokerstars-hand-convert"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.9"
dependencies = [
    "pydantic>=2.11.7",
    "typing>=3.10.0.0",
]

[dependency-groups]
dev = [
    "pytest>=8.4.2",
]
